name: my_DiaryApp
description: Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  intl: ^0.15.8
  http: ^0.12.2
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^1.3.0
  shared_preferences: ^0.5.12+4



  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/

  fonts:
  - family: Apple Juiced
    fonts:
    - asset: fonts/applejuiced.ttf

  - family: Billbrd
    fonts:
    - asset: fonts/billbrd.ttf

  - family: Ebbing
    fonts:
    - asset: fonts/Ebbing.ttf

  - family: Tw Cent
    fonts:
    - asset: fonts/TwCent.ttf

  - family: Caveat
    fonts:
    - asset: fonts/Caveat-Regular.ttf

  - family: Great Vibes
    fonts:
    - asset: fonts/GreatVibes-Regular.ttf

  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: Satisfy
    fonts:
    - asset: fonts/Satisfy-Regular.ttf

  - family: Yellowtail
    fonts:
    - asset: fonts/Yellowtail-Regular.ttf

  - family: Dosis
    fonts:
    - asset: fonts/Dosis-VariableFont_wght.ttf

  - family: Kosugi Maru
    fonts:
    - asset: fonts/KosugiMaru-Regular.ttf

  - family: Source Sans Pro
    fonts:
    - asset: fonts/SourceSansPro-SemiBoldItalic.ttf